arb-dir: lib/shared_layers/localization/l10n_arb_files
synthetic-package: false
output-dir: lib/shared_layers/localization/generated
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart