// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness/test/modules/home/data/data_sources_imp/random_exercises/random_exercises_remote_data_source_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:super_fitness/modules/home/data/api/api_client/home_api_client.dart'
    as _i5;
import 'package:super_fitness/modules/home/data/models/random_exercises/random_exercises_response_dto.dart'
    as _i2;
import 'package:super_fitness/modules/home/data/models/workouts/get_all_muscles_group_response.dart'
    as _i3;
import 'package:super_fitness/modules/home/data/models/workouts/muscle_group_workouts.dart'
    as _i4;
import 'package:super_fitness/shared_layers/localization/l10n_manager/localization_manager.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRandomExercisesResponseDto_0 extends _i1.SmartFake
    implements _i2.RandomExercisesResponseDto {
  _FakeRandomExercisesResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetMusclesGroupResponse_1 extends _i1.SmartFake
    implements _i3.GetMusclesGroupResponse {
  _FakeGetMusclesGroupResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMuscleGroupWorkoutsResponse_2 extends _i1.SmartFake
    implements _i4.MuscleGroupWorkoutsResponse {
  _FakeMuscleGroupWorkoutsResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeApiClient extends _i1.Mock implements _i5.HomeApiClient {
  MockHomeApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.RandomExercisesResponseDto> getRandomExercises({
    required Map<String, dynamic>? queries,
    required String? languageCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRandomExercises, [], {
              #queries: queries,
              #languageCode: languageCode,
            }),
            returnValue: _i6.Future<_i2.RandomExercisesResponseDto>.value(
              _FakeRandomExercisesResponseDto_0(
                this,
                Invocation.method(#getRandomExercises, [], {
                  #queries: queries,
                  #languageCode: languageCode,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.RandomExercisesResponseDto>);

  @override
  _i6.Future<_i3.GetMusclesGroupResponse> getMusclesGroup() =>
      (super.noSuchMethod(
            Invocation.method(#getMusclesGroup, []),
            returnValue: _i6.Future<_i3.GetMusclesGroupResponse>.value(
              _FakeGetMusclesGroupResponse_1(
                this,
                Invocation.method(#getMusclesGroup, []),
              ),
            ),
          )
          as _i6.Future<_i3.GetMusclesGroupResponse>);

  @override
  _i6.Future<_i4.MuscleGroupWorkoutsResponse> getMusclesGroupWorkouts(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMusclesGroupWorkouts, [id]),
            returnValue: _i6.Future<_i4.MuscleGroupWorkoutsResponse>.value(
              _FakeMuscleGroupWorkoutsResponse_2(
                this,
                Invocation.method(#getMusclesGroupWorkouts, [id]),
              ),
            ),
          )
          as _i6.Future<_i4.MuscleGroupWorkoutsResponse>);
}

/// A class which mocks [LocalizationManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalizationManager extends _i1.Mock
    implements _i7.LocalizationManager {
  MockLocalizationManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get currentLocale =>
      (super.noSuchMethod(
            Invocation.getter(#currentLocale),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#currentLocale),
            ),
          )
          as String);

  @override
  bool get isEnglish =>
      (super.noSuchMethod(Invocation.getter(#isEnglish), returnValue: false)
          as bool);

  @override
  set currentLocale(String? _currentLocale) => super.noSuchMethod(
    Invocation.setter(#currentLocale, _currentLocale),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> changeLocal(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#changeLocal, [languageCode]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getSavedLocal() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedLocal, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
