// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness/test/modules/home/domain/use_cases/random_exercises/get_ten_random_exerciese_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:super_fitness/core/apis/api_result/api_result.dart' as _i4;
import 'package:super_fitness/modules/home/domain/entities/random_exercises/random_exercises_request_entity.dart'
    as _i6;
import 'package:super_fitness/modules/home/domain/entities/random_exercises/random_exercises_response_entity.dart'
    as _i5;
import 'package:super_fitness/modules/home/domain/repositories_contracts/random_exercises/random_exercise_repo.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RandomExercisesRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockRandomExercisesRepo extends _i1.Mock
    implements _i2.RandomExercisesRepo {
  MockRandomExercisesRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.RandomExercisesResponseEntity>>
  getRandomExercises({
    required _i6.RandomExercisesRequestEntity? exercisesRequestEntity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRandomExercises, [], {
              #exercisesRequestEntity: exercisesRequestEntity,
            }),
            returnValue: _i3.Future<
              _i4.ApiResult<_i5.RandomExercisesResponseEntity>
            >.value(
              _i7.dummyValue<_i4.ApiResult<_i5.RandomExercisesResponseEntity>>(
                this,
                Invocation.method(#getRandomExercises, [], {
                  #exercisesRequestEntity: exercisesRequestEntity,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.RandomExercisesResponseEntity>>);
}
