// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness/test/modules/food_details/ui/view_model/food_details_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:super_fitness/core/apis/api_result/api_result.dart' as _i5;
import 'package:super_fitness/modules/food_details/domain/entities/food_details_entity.dart'
    as _i6;
import 'package:super_fitness/modules/food_details/domain/repo_contract/food_details_repo_contract.dart'
    as _i2;
import 'package:super_fitness/modules/food_details/domain/usecases/get_food_details_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFoodDetailsRepo_0 extends _i1.SmartFake
    implements _i2.FoodDetailsRepo {
  _FakeFoodDetailsRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetFoodDetailsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFoodDetailsUseCase extends _i1.Mock
    implements _i3.GetFoodDetailsUseCase {
  MockGetFoodDetailsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FoodDetailsRepo get foodDetailsRepo =>
      (super.noSuchMethod(
            Invocation.getter(#foodDetailsRepo),
            returnValue: _FakeFoodDetailsRepo_0(
              this,
              Invocation.getter(#foodDetailsRepo),
            ),
          )
          as _i2.FoodDetailsRepo);

  @override
  _i4.Future<_i5.ApiResult<_i6.FoodDetailsEntity>> execute(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue: _i4.Future<_i5.ApiResult<_i6.FoodDetailsEntity>>.value(
              _i7.dummyValue<_i5.ApiResult<_i6.FoodDetailsEntity>>(
                this,
                Invocation.method(#execute, [id]),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.FoodDetailsEntity>>);
}
