// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness/test/modules/onboarding/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:flutter/foundation.dart' as _i11;
import 'package:flutter/widgets.dart' as _i5;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:super_fitness/core/validation/validation_functions.dart'
    as _i10;
import 'package:super_fitness/shared_layers/localization/generated/app_localizations.dart'
    as _i3;
import 'package:super_fitness/shared_layers/localization/l10n_manager/localization_manager.dart'
    as _i6;
import 'package:super_fitness/shared_layers/storage/implementation/flutter_secure_storage_service_imp.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFlutterSecureStorage_0 extends _i1.SmartFake
    implements _i2.FlutterSecureStorage {
  _FakeFlutterSecureStorage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_1 extends _i1.SmartFake implements _i2.IOSOptions {
  _FakeIOSOptions_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_2 extends _i1.SmartFake
    implements _i2.AndroidOptions {
  _FakeAndroidOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_3 extends _i1.SmartFake implements _i2.LinuxOptions {
  _FakeLinuxOptions_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_4 extends _i1.SmartFake
    implements _i2.WindowsOptions {
  _FakeWindowsOptions_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_5 extends _i1.SmartFake implements _i2.WebOptions {
  _FakeWebOptions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_6 extends _i1.SmartFake implements _i2.MacOsOptions {
  _FakeMacOsOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppLocalizations].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalizations extends _i1.Mock implements _i3.AppLocalizations {
  MockAppLocalizations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get localeName =>
      (super.noSuchMethod(
            Invocation.getter(#localeName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#localeName),
            ),
          )
          as String);

  @override
  String get errorMessages________ =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessages________),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#errorMessages________),
            ),
          )
          as String);

  @override
  String get connectionTimeout =>
      (super.noSuchMethod(
            Invocation.getter(#connectionTimeout),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#connectionTimeout),
            ),
          )
          as String);

  @override
  String get sendTimeout =>
      (super.noSuchMethod(
            Invocation.getter(#sendTimeout),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#sendTimeout),
            ),
          )
          as String);

  @override
  String get receiveTimeout =>
      (super.noSuchMethod(
            Invocation.getter(#receiveTimeout),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#receiveTimeout),
            ),
          )
          as String);

  @override
  String get cancel =>
      (super.noSuchMethod(
            Invocation.getter(#cancel),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#cancel),
            ),
          )
          as String);

  @override
  String get connectionError =>
      (super.noSuchMethod(
            Invocation.getter(#connectionError),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#connectionError),
            ),
          )
          as String);

  @override
  String get unknownError =>
      (super.noSuchMethod(
            Invocation.getter(#unknownError),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#unknownError),
            ),
          )
          as String);

  @override
  String get badCertificate =>
      (super.noSuchMethod(
            Invocation.getter(#badCertificate),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#badCertificate),
            ),
          )
          as String);

  @override
  String get somethingWentWrong =>
      (super.noSuchMethod(
            Invocation.getter(#somethingWentWrong),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#somethingWentWrong),
            ),
          )
          as String);

  @override
  String get validationFunctions____________ =>
      (super.noSuchMethod(
            Invocation.getter(#validationFunctions____________),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#validationFunctions____________),
            ),
          )
          as String);

  @override
  String get pleaseEnterName =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterName),
            ),
          )
          as String);

  @override
  String get pleaseEnterUserName =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterUserName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterUserName),
            ),
          )
          as String);

  @override
  String get userNameLength =>
      (super.noSuchMethod(
            Invocation.getter(#userNameLength),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#userNameLength),
            ),
          )
          as String);

  @override
  String get userNameRules =>
      (super.noSuchMethod(
            Invocation.getter(#userNameRules),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#userNameRules),
            ),
          )
          as String);

  @override
  String get pleaseEnterFirstName =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterFirstName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterFirstName),
            ),
          )
          as String);

  @override
  String get pleaseEnterLastName =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterLastName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterLastName),
            ),
          )
          as String);

  @override
  String get namesRules =>
      (super.noSuchMethod(
            Invocation.getter(#namesRules),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#namesRules),
            ),
          )
          as String);

  @override
  String get pleaseEnterEmail =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterEmail),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterEmail),
            ),
          )
          as String);

  @override
  String get pleaseEnterValidEmail =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterValidEmail),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterValidEmail),
            ),
          )
          as String);

  @override
  String get pleaseEnterPhoneNumber =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterPhoneNumber),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterPhoneNumber),
            ),
          )
          as String);

  @override
  String get phoneNumberRules =>
      (super.noSuchMethod(
            Invocation.getter(#phoneNumberRules),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#phoneNumberRules),
            ),
          )
          as String);

  @override
  String get pleaseEnterPassword =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterPassword),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterPassword),
            ),
          )
          as String);

  @override
  String get passwordLength =>
      (super.noSuchMethod(
            Invocation.getter(#passwordLength),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#passwordLength),
            ),
          )
          as String);

  @override
  String get uppercaseRulePassword =>
      (super.noSuchMethod(
            Invocation.getter(#uppercaseRulePassword),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#uppercaseRulePassword),
            ),
          )
          as String);

  @override
  String get lowercaseRulePassword =>
      (super.noSuchMethod(
            Invocation.getter(#lowercaseRulePassword),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#lowercaseRulePassword),
            ),
          )
          as String);

  @override
  String get digitRulePassword =>
      (super.noSuchMethod(
            Invocation.getter(#digitRulePassword),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#digitRulePassword),
            ),
          )
          as String);

  @override
  String get specialCharactersRulePassword =>
      (super.noSuchMethod(
            Invocation.getter(#specialCharactersRulePassword),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#specialCharactersRulePassword),
            ),
          )
          as String);

  @override
  String get pleaseConfirmPassword =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseConfirmPassword),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#pleaseConfirmPassword),
            ),
          )
          as String);

  @override
  String get namesLengthRule =>
      (super.noSuchMethod(
            Invocation.getter(#namesLengthRule),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#namesLengthRule),
            ),
          )
          as String);

  @override
  String get noMatch =>
      (super.noSuchMethod(
            Invocation.getter(#noMatch),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#noMatch),
            ),
          )
          as String);

  @override
  String get pleaseEnterAddress =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterAddress),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterAddress),
            ),
          )
          as String);

  @override
  String get forgetPassword____________ =>
      (super.noSuchMethod(
            Invocation.getter(#forgetPassword____________),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#forgetPassword____________),
            ),
          )
          as String);

  @override
  String get emailHint =>
      (super.noSuchMethod(
            Invocation.getter(#emailHint),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#emailHint),
            ),
          )
          as String);

  @override
  String get passwordHint =>
      (super.noSuchMethod(
            Invocation.getter(#passwordHint),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#passwordHint),
            ),
          )
          as String);

  @override
  String get confirmPasswordHint =>
      (super.noSuchMethod(
            Invocation.getter(#confirmPasswordHint),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#confirmPasswordHint),
            ),
          )
          as String);

  @override
  String get gender =>
      (super.noSuchMethod(
            Invocation.getter(#gender),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#gender),
            ),
          )
          as String);

  @override
  String get removedImage =>
      (super.noSuchMethod(
            Invocation.getter(#removedImage),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#removedImage),
            ),
          )
          as String);

  @override
  String get forgetPasswordDescription =>
      (super.noSuchMethod(
            Invocation.getter(#forgetPasswordDescription),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#forgetPasswordDescription),
            ),
          )
          as String);

  @override
  String get confirm =>
      (super.noSuchMethod(
            Invocation.getter(#confirm),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#confirm),
            ),
          )
          as String);

  @override
  String get codeSendTitle =>
      (super.noSuchMethod(
            Invocation.getter(#codeSendTitle),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#codeSendTitle),
            ),
          )
          as String);

  @override
  String get otpScreenTitle =>
      (super.noSuchMethod(
            Invocation.getter(#otpScreenTitle),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#otpScreenTitle),
            ),
          )
          as String);

  @override
  String get otpScreenDescription =>
      (super.noSuchMethod(
            Invocation.getter(#otpScreenDescription),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#otpScreenDescription),
            ),
          )
          as String);

  @override
  String get didNotReceiveOtp =>
      (super.noSuchMethod(
            Invocation.getter(#didNotReceiveOtp),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#didNotReceiveOtp),
            ),
          )
          as String);

  @override
  String get resend =>
      (super.noSuchMethod(
            Invocation.getter(#resend),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#resend),
            ),
          )
          as String);

  @override
  String get codeValid =>
      (super.noSuchMethod(
            Invocation.getter(#codeValid),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#codeValid),
            ),
          )
          as String);

  @override
  String get codeNotValid =>
      (super.noSuchMethod(
            Invocation.getter(#codeNotValid),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#codeNotValid),
            ),
          )
          as String);

  @override
  String get resetPasswordScreenDescription =>
      (super.noSuchMethod(
            Invocation.getter(#resetPasswordScreenDescription),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#resetPasswordScreenDescription),
            ),
          )
          as String);

  @override
  String get resetPasswordScreenTitle =>
      (super.noSuchMethod(
            Invocation.getter(#resetPasswordScreenTitle),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#resetPasswordScreenTitle),
            ),
          )
          as String);

  @override
  String get newPassword =>
      (super.noSuchMethod(
            Invocation.getter(#newPassword),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#newPassword),
            ),
          )
          as String);

  @override
  String get confirmNewPassword =>
      (super.noSuchMethod(
            Invocation.getter(#confirmNewPassword),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#confirmNewPassword),
            ),
          )
          as String);

  @override
  String get yourPasswordChanged =>
      (super.noSuchMethod(
            Invocation.getter(#yourPasswordChanged),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#yourPasswordChanged),
            ),
          )
          as String);

  @override
  String get enterEmail =>
      (super.noSuchMethod(
            Invocation.getter(#enterEmail),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#enterEmail),
            ),
          )
          as String);

  @override
  String get enterPassword =>
      (super.noSuchMethod(
            Invocation.getter(#enterPassword),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#enterPassword),
            ),
          )
          as String);

  @override
  String get forgetPassword =>
      (super.noSuchMethod(
            Invocation.getter(#forgetPassword),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#forgetPassword),
            ),
          )
          as String);

  @override
  String get pleaseEnterValidAddress =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterValidAddress),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterValidAddress),
            ),
          )
          as String);

  @override
  String get skip =>
      (super.noSuchMethod(
            Invocation.getter(#skip),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#skip)),
          )
          as String);

  @override
  String get back =>
      (super.noSuchMethod(
            Invocation.getter(#back),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#back)),
          )
          as String);

  @override
  String get doIt =>
      (super.noSuchMethod(
            Invocation.getter(#doIt),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#doIt)),
          )
          as String);

  @override
  String get priceOfExcellence =>
      (super.noSuchMethod(
            Invocation.getter(#priceOfExcellence),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#priceOfExcellence),
            ),
          )
          as String);

  @override
  String get isDiscipline =>
      (super.noSuchMethod(
            Invocation.getter(#isDiscipline),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#isDiscipline),
            ),
          )
          as String);

  @override
  String get fitnessHasNeverBeenSo =>
      (super.noSuchMethod(
            Invocation.getter(#fitnessHasNeverBeenSo),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#fitnessHasNeverBeenSo),
            ),
          )
          as String);

  @override
  String get muchFun =>
      (super.noSuchMethod(
            Invocation.getter(#muchFun),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#muchFun),
            ),
          )
          as String);

  @override
  String get noMoreExcuses =>
      (super.noSuchMethod(
            Invocation.getter(#noMoreExcuses),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#noMoreExcuses),
            ),
          )
          as String);

  @override
  String get doItNow =>
      (super.noSuchMethod(
            Invocation.getter(#doItNow),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#doItNow),
            ),
          )
          as String);

  @override
  String get loremIpsumDolorSitAmetConsectetureuUrna =>
      (super.noSuchMethod(
            Invocation.getter(#loremIpsumDolorSitAmetConsectetureuUrna),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#loremIpsumDolorSitAmetConsectetureuUrna),
            ),
          )
          as String);

  @override
  String get utGravidaQuisIdPretiumPurusMaurisMassa =>
      (super.noSuchMethod(
            Invocation.getter(#utGravidaQuisIdPretiumPurusMaurisMassa),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#utGravidaQuisIdPretiumPurusMaurisMassa),
            ),
          )
          as String);

  @override
  String get pleaseEnterValidRecipient =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterValidRecipient),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterValidRecipient),
            ),
          )
          as String);

  @override
  String get home =>
      (super.noSuchMethod(
            Invocation.getter(#home),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#home)),
          )
          as String);

  @override
  String get chatAI =>
      (super.noSuchMethod(
            Invocation.getter(#chatAI),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#chatAI),
            ),
          )
          as String);

  @override
  String get forgotPassword =>
      (super.noSuchMethod(
            Invocation.getter(#forgotPassword),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#forgotPassword),
            ),
          )
          as String);

  @override
  String get noAccount =>
      (super.noSuchMethod(
            Invocation.getter(#noAccount),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#noAccount),
            ),
          )
          as String);

  @override
  String get success =>
      (super.noSuchMethod(
            Invocation.getter(#success),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#success),
            ),
          )
          as String);

  @override
  String get loginSuccessfully =>
      (super.noSuchMethod(
            Invocation.getter(#loginSuccessfully),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#loginSuccessfully),
            ),
          )
          as String);

  @override
  String get welcomeBack =>
      (super.noSuchMethod(
            Invocation.getter(#welcomeBack),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#welcomeBack),
            ),
          )
          as String);

  @override
  String get registerScreen________ =>
      (super.noSuchMethod(
            Invocation.getter(#registerScreen________),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#registerScreen________),
            ),
          )
          as String);

  @override
  String get heyThere =>
      (super.noSuchMethod(
            Invocation.getter(#heyThere),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#heyThere),
            ),
          )
          as String);

  @override
  String get createAnAccount =>
      (super.noSuchMethod(
            Invocation.getter(#createAnAccount),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#createAnAccount),
            ),
          )
          as String);

  @override
  String get register =>
      (super.noSuchMethod(
            Invocation.getter(#register),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#register),
            ),
          )
          as String);

  @override
  String get firstName =>
      (super.noSuchMethod(
            Invocation.getter(#firstName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#firstName),
            ),
          )
          as String);

  @override
  String get lastName =>
      (super.noSuchMethod(
            Invocation.getter(#lastName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#lastName),
            ),
          )
          as String);

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get password =>
      (super.noSuchMethod(
            Invocation.getter(#password),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#password),
            ),
          )
          as String);

  @override
  String get confirmPassword =>
      (super.noSuchMethod(
            Invocation.getter(#confirmPassword),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#confirmPassword),
            ),
          )
          as String);

  @override
  String get or =>
      (super.noSuchMethod(
            Invocation.getter(#or),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#or)),
          )
          as String);

  @override
  String get alreadyHaveAccount =>
      (super.noSuchMethod(
            Invocation.getter(#alreadyHaveAccount),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#alreadyHaveAccount),
            ),
          )
          as String);

  @override
  String get login =>
      (super.noSuchMethod(
            Invocation.getter(#login),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#login),
            ),
          )
          as String);

  @override
  String get successfullyRegistered =>
      (super.noSuchMethod(
            Invocation.getter(#successfullyRegistered),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#successfullyRegistered),
            ),
          )
          as String);

  @override
  String get error =>
      (super.noSuchMethod(
            Invocation.getter(#error),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#error),
            ),
          )
          as String);

  @override
  String get tellUsAboutYourself =>
      (super.noSuchMethod(
            Invocation.getter(#tellUsAboutYourself),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#tellUsAboutYourself),
            ),
          )
          as String);

  @override
  String get weNeedToKnowYourGender =>
      (super.noSuchMethod(
            Invocation.getter(#weNeedToKnowYourGender),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#weNeedToKnowYourGender),
            ),
          )
          as String);

  @override
  String get howOldAreYou =>
      (super.noSuchMethod(
            Invocation.getter(#howOldAreYou),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#howOldAreYou),
            ),
          )
          as String);

  @override
  String get whatIsYourWeight =>
      (super.noSuchMethod(
            Invocation.getter(#whatIsYourWeight),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#whatIsYourWeight),
            ),
          )
          as String);

  @override
  String get thisHelpsUsCreateYourPersonalizedPlan =>
      (super.noSuchMethod(
            Invocation.getter(#thisHelpsUsCreateYourPersonalizedPlan),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#thisHelpsUsCreateYourPersonalizedPlan),
            ),
          )
          as String);

  @override
  String get whatIsYourHeight =>
      (super.noSuchMethod(
            Invocation.getter(#whatIsYourHeight),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#whatIsYourHeight),
            ),
          )
          as String);

  @override
  String get whatIsYourGoal =>
      (super.noSuchMethod(
            Invocation.getter(#whatIsYourGoal),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#whatIsYourGoal),
            ),
          )
          as String);

  @override
  String get yourPhysicalActivityLevel =>
      (super.noSuchMethod(
            Invocation.getter(#yourPhysicalActivityLevel),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#yourPhysicalActivityLevel),
            ),
          )
          as String);

  @override
  String get activityLevel =>
      (super.noSuchMethod(
            Invocation.getter(#activityLevel),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#activityLevel),
            ),
          )
          as String);

  @override
  String get male =>
      (super.noSuchMethod(
            Invocation.getter(#male),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#male)),
          )
          as String);

  @override
  String get female =>
      (super.noSuchMethod(
            Invocation.getter(#female),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#female),
            ),
          )
          as String);

  @override
  String get next =>
      (super.noSuchMethod(
            Invocation.getter(#next),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#next)),
          )
          as String);

  @override
  String get year =>
      (super.noSuchMethod(
            Invocation.getter(#year),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#year)),
          )
          as String);

  @override
  String get kg =>
      (super.noSuchMethod(
            Invocation.getter(#kg),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#kg)),
          )
          as String);

  @override
  String get cm =>
      (super.noSuchMethod(
            Invocation.getter(#cm),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#cm)),
          )
          as String);

  @override
  String get gainWeight =>
      (super.noSuchMethod(
            Invocation.getter(#gainWeight),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#gainWeight),
            ),
          )
          as String);

  @override
  String get loseWeight =>
      (super.noSuchMethod(
            Invocation.getter(#loseWeight),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#loseWeight),
            ),
          )
          as String);

  @override
  String get getFitter =>
      (super.noSuchMethod(
            Invocation.getter(#getFitter),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#getFitter),
            ),
          )
          as String);

  @override
  String get gainMoreFlexible =>
      (super.noSuchMethod(
            Invocation.getter(#gainMoreFlexible),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#gainMoreFlexible),
            ),
          )
          as String);

  @override
  String get learnTheBasic =>
      (super.noSuchMethod(
            Invocation.getter(#learnTheBasic),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#learnTheBasic),
            ),
          )
          as String);

  @override
  String get rookie =>
      (super.noSuchMethod(
            Invocation.getter(#rookie),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#rookie),
            ),
          )
          as String);

  @override
  String get beginner =>
      (super.noSuchMethod(
            Invocation.getter(#beginner),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#beginner),
            ),
          )
          as String);

  @override
  String get intermediate =>
      (super.noSuchMethod(
            Invocation.getter(#intermediate),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#intermediate),
            ),
          )
          as String);

  @override
  String get advanced =>
      (super.noSuchMethod(
            Invocation.getter(#advanced),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#advanced),
            ),
          )
          as String);

  @override
  String get trueBeast =>
      (super.noSuchMethod(
            Invocation.getter(#trueBeast),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#trueBeast),
            ),
          )
          as String);

  @override
  String get appSections___________ =>
      (super.noSuchMethod(
            Invocation.getter(#appSections___________),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#appSections___________),
            ),
          )
          as String);

  @override
  String get explore =>
      (super.noSuchMethod(
            Invocation.getter(#explore),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#explore),
            ),
          )
          as String);

  @override
  String get aiChat =>
      (super.noSuchMethod(
            Invocation.getter(#aiChat),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#aiChat),
            ),
          )
          as String);

  @override
  String get workouts =>
      (super.noSuchMethod(
            Invocation.getter(#workouts),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#workouts),
            ),
          )
          as String);

  @override
  String get sendOtp =>
      (super.noSuchMethod(
            Invocation.getter(#sendOtp),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#sendOtp),
            ),
          )
          as String);

  @override
  String get resetPassDesc =>
      (super.noSuchMethod(
            Invocation.getter(#resetPassDesc),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#resetPassDesc),
            ),
          )
          as String);

  @override
  String get createNewPassword =>
      (super.noSuchMethod(
            Invocation.getter(#createNewPassword),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#createNewPassword),
            ),
          )
          as String);

  @override
  String get done =>
      (super.noSuchMethod(
            Invocation.getter(#done),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#done)),
          )
          as String);

  @override
  String get oTpCode =>
      (super.noSuchMethod(
            Invocation.getter(#oTpCode),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#oTpCode),
            ),
          )
          as String);

  @override
  String get enterOtpCode =>
      (super.noSuchMethod(
            Invocation.getter(#enterOtpCode),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#enterOtpCode),
            ),
          )
          as String);

  @override
  String get successEmailVerified =>
      (super.noSuchMethod(
            Invocation.getter(#successEmailVerified),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#successEmailVerified),
            ),
          )
          as String);

  @override
  String get foodRecommendation =>
      (super.noSuchMethod(
            Invocation.getter(#foodRecommendation),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#foodRecommendation),
            ),
          )
          as String);

  @override
  String get noVideoProvide =>
      (super.noSuchMethod(
            Invocation.getter(#noVideoProvide),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#noVideoProvide),
            ),
          )
          as String);

  @override
  String get noFoodRecommendation =>
      (super.noSuchMethod(
            Invocation.getter(#noFoodRecommendation),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#noFoodRecommendation),
            ),
          )
          as String);

  @override
  String get noWorkoutsAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#noWorkoutsAvailable),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#noWorkoutsAvailable),
            ),
          )
          as String);

  @override
  String get homePage_________ =>
      (super.noSuchMethod(
            Invocation.getter(#homePage_________),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#homePage_________),
            ),
          )
          as String);

  @override
  String get startYourDayMessage =>
      (super.noSuchMethod(
            Invocation.getter(#startYourDayMessage),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#startYourDayMessage),
            ),
          )
          as String);

  @override
  String get category =>
      (super.noSuchMethod(
            Invocation.getter(#category),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#category),
            ),
          )
          as String);

  @override
  String get gym =>
      (super.noSuchMethod(
            Invocation.getter(#gym),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#gym)),
          )
          as String);

  @override
  String get fitness =>
      (super.noSuchMethod(
            Invocation.getter(#fitness),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#fitness),
            ),
          )
          as String);

  @override
  String get yoga =>
      (super.noSuchMethod(
            Invocation.getter(#yoga),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#yoga)),
          )
          as String);

  @override
  String get aerobics =>
      (super.noSuchMethod(
            Invocation.getter(#aerobics),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#aerobics),
            ),
          )
          as String);

  @override
  String get trainer =>
      (super.noSuchMethod(
            Invocation.getter(#trainer),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#trainer),
            ),
          )
          as String);

  @override
  String get recommendationToDay =>
      (super.noSuchMethod(
            Invocation.getter(#recommendationToDay),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#recommendationToDay),
            ),
          )
          as String);

  @override
  String get noData =>
      (super.noSuchMethod(
            Invocation.getter(#noData),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#noData),
            ),
          )
          as String);

  @override
  String get upcomingWorkouts =>
      (super.noSuchMethod(
            Invocation.getter(#upcomingWorkouts),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#upcomingWorkouts),
            ),
          )
          as String);

  @override
  String get seeAll =>
      (super.noSuchMethod(
            Invocation.getter(#seeAll),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#seeAll),
            ),
          )
          as String);

  @override
  String get recommendationForYou =>
      (super.noSuchMethod(
            Invocation.getter(#recommendationForYou),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#recommendationForYou),
            ),
          )
          as String);

  @override
  String get unknown =>
      (super.noSuchMethod(
            Invocation.getter(#unknown),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#unknown),
            ),
          )
          as String);

  @override
  String hiUser(Object? userName) =>
      (super.noSuchMethod(
            Invocation.method(#hiUser, [userName]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#hiUser, [userName]),
            ),
          )
          as String);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i5.NavigatorObserver {
  MockNavigatorObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didPush(_i5.Route<dynamic>? route, _i5.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPush, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didPop(_i5.Route<dynamic>? route, _i5.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i5.Route<dynamic>? route,
    _i5.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i5.Route<dynamic>? newRoute,
    _i5.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i5.Route<dynamic>? topRoute,
    _i5.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i5.Route<dynamic>? route,
    _i5.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LocalizationManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalizationManager extends _i1.Mock
    implements _i6.LocalizationManager {
  MockLocalizationManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get currentLocale =>
      (super.noSuchMethod(
            Invocation.getter(#currentLocale),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#currentLocale),
            ),
          )
          as String);

  @override
  bool get isEnglish =>
      (super.noSuchMethod(Invocation.getter(#isEnglish), returnValue: false)
          as bool);

  @override
  set currentLocale(String? _currentLocale) => super.noSuchMethod(
    Invocation.setter(#currentLocale, _currentLocale),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> changeLocal(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#changeLocal, [languageCode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> getSavedLocal() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedLocal, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SecureStorageServiceImp].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageServiceImp extends _i1.Mock
    implements _i9.SecureStorageServiceImp {
  MockSecureStorageServiceImp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlutterSecureStorage get storageInstance =>
      (super.noSuchMethod(
            Invocation.getter(#storageInstance),
            returnValue: _FakeFlutterSecureStorage_0(
              this,
              Invocation.getter(#storageInstance),
            ),
          )
          as _i2.FlutterSecureStorage);

  @override
  void setStringValue(String? key, String? value) => super.noSuchMethod(
    Invocation.method(#setStringValue, [key, value]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<String?> getStringValue(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getStringValue, [key]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> deleteValue(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#deleteValue, [key]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [ValidateFunctions].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidateFunctions extends _i1.Mock implements _i10.ValidateFunctions {
  MockValidateFunctions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set appLocalizations(_i3.AppLocalizations? appLocalizations) =>
      super.noSuchMethod(
        Invocation.setter(#appLocalizations, appLocalizations),
        returnValueForMissingStub: null,
      );

  @override
  String? validationOfFirstOrLastName(
    String? inputText, {
    bool? isFirstName = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #validationOfFirstOrLastName,
              [inputText],
              {#isFirstName: isFirstName},
            ),
          )
          as String?);

  @override
  String? validationOfConfirmPassword(
    String? inputText,
    String? passwordToMatchWith,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validationOfConfirmPassword, [
              inputText,
              passwordToMatchWith,
            ]),
          )
          as String?);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i2.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_1(this, Invocation.getter(#iOptions)),
          )
          as _i2.IOSOptions);

  @override
  _i2.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_2(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i2.AndroidOptions);

  @override
  _i2.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_3(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i2.LinuxOptions);

  @override
  _i2.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_4(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i2.WindowsOptions);

  @override
  _i2.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_5(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i2.WebOptions);

  @override
  _i2.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_6(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i2.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i11.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i11.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> write({
    required String? key,
    required String? value,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> read({
    required String? key,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<bool> containsKey({
    required String? key,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> delete({
    required String? key,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, String>> readAll({
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i7.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i7.Future<Map<String, String>>);

  @override
  _i7.Future<void> deleteAll({
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i7.Future<bool?>.value(),
          )
          as _i7.Future<bool?>);
}
