// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness/test/modules/edit_profile/ui/screens/edit_profile_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i12;
import 'dart:ui' as _i14;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:super_fitness/core/apis/api_result/api_result.dart' as _i5;
import 'package:super_fitness/core/validation/validation_functions.dart'
    as _i16;
import 'package:super_fitness/modules/edit_profile/domain/entity/edit_info.dart'
    as _i9;
import 'package:super_fitness/modules/edit_profile/domain/entity/get_data_entity.dart'
    as _i6;
import 'package:super_fitness/modules/edit_profile/domain/entity/upload_image_response_entity.dart'
    as _i11;
import 'package:super_fitness/modules/edit_profile/domain/repo/upload_image.dart'
    as _i2;
import 'package:super_fitness/modules/edit_profile/domain/usecase/edit_info_usecase.dart'
    as _i8;
import 'package:super_fitness/modules/edit_profile/domain/usecase/get_data_usecase.dart'
    as _i3;
import 'package:super_fitness/modules/edit_profile/domain/usecase/upload_image.dart'
    as _i10;
import 'package:super_fitness/shared_layers/localization/generated/app_localizations.dart'
    as _i15;
import 'package:super_fitness/shared_layers/localization/l10n_manager/localization_manager.dart'
    as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUploadImageRepo_0 extends _i1.SmartFake
    implements _i2.UploadImageRepo {
  _FakeUploadImageRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetUserDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserDataUseCase extends _i1.Mock
    implements _i3.GetUserDataUseCase {
  MockGetUserDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResult<_i6.GetDataEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.ApiResult<_i6.GetDataEntity>>.value(
              _i7.dummyValue<_i5.ApiResult<_i6.GetDataEntity>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.GetDataEntity>>);
}

/// A class which mocks [EditInfoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditInfoUseCase extends _i1.Mock implements _i8.EditInfoUseCase {
  MockEditInfoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResult<_i9.EditMyInfoEntity>> call(
    String? firstName,
    String? lastName,
    String? email,
    String? goal,
    String? weight,
    String? level,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [
              firstName,
              lastName,
              email,
              goal,
              weight,
              level,
            ]),
            returnValue: _i4.Future<_i5.ApiResult<_i9.EditMyInfoEntity>>.value(
              _i7.dummyValue<_i5.ApiResult<_i9.EditMyInfoEntity>>(
                this,
                Invocation.method(#call, [
                  firstName,
                  lastName,
                  email,
                  goal,
                  weight,
                  level,
                ]),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i9.EditMyInfoEntity>>);
}

/// A class which mocks [UploadImageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadImageUseCase extends _i1.Mock
    implements _i10.UploadImageUseCase {
  MockUploadImageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UploadImageRepo get uploadImageRepo =>
      (super.noSuchMethod(
            Invocation.getter(#uploadImageRepo),
            returnValue: _FakeUploadImageRepo_0(
              this,
              Invocation.getter(#uploadImageRepo),
            ),
          )
          as _i2.UploadImageRepo);

  @override
  set uploadImageRepo(_i2.UploadImageRepo? _uploadImageRepo) =>
      super.noSuchMethod(
        Invocation.setter(#uploadImageRepo, _uploadImageRepo),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i5.ApiResult<_i11.UploadImageResponseEntity?>> execute({
    required _i12.File? imageFile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {#imageFile: imageFile}),
            returnValue: _i4.Future<
              _i5.ApiResult<_i11.UploadImageResponseEntity?>
            >.value(
              _i7.dummyValue<_i5.ApiResult<_i11.UploadImageResponseEntity?>>(
                this,
                Invocation.method(#execute, [], {#imageFile: imageFile}),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i11.UploadImageResponseEntity?>>);
}

/// A class which mocks [LocalizationManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalizationManager extends _i1.Mock
    implements _i13.LocalizationManager {
  MockLocalizationManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get currentLocale =>
      (super.noSuchMethod(
            Invocation.getter(#currentLocale),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#currentLocale),
            ),
          )
          as String);

  @override
  bool get isEnglish =>
      (super.noSuchMethod(Invocation.getter(#isEnglish), returnValue: false)
          as bool);

  @override
  set currentLocale(String? _currentLocale) => super.noSuchMethod(
    Invocation.setter(#currentLocale, _currentLocale),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> changeLocal(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#changeLocal, [languageCode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getSavedLocal() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedLocal, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AppLocalizations].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalizations extends _i1.Mock implements _i15.AppLocalizations {
  MockAppLocalizations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get localeName =>
      (super.noSuchMethod(
            Invocation.getter(#localeName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#localeName),
            ),
          )
          as String);

  @override
  String get errorMessages________ =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessages________),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#errorMessages________),
            ),
          )
          as String);

  @override
  String get connectionTimeout =>
      (super.noSuchMethod(
            Invocation.getter(#connectionTimeout),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#connectionTimeout),
            ),
          )
          as String);

  @override
  String get sendTimeout =>
      (super.noSuchMethod(
            Invocation.getter(#sendTimeout),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#sendTimeout),
            ),
          )
          as String);

  @override
  String get receiveTimeout =>
      (super.noSuchMethod(
            Invocation.getter(#receiveTimeout),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#receiveTimeout),
            ),
          )
          as String);

  @override
  String get cancel =>
      (super.noSuchMethod(
            Invocation.getter(#cancel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#cancel),
            ),
          )
          as String);

  @override
  String get connectionError =>
      (super.noSuchMethod(
            Invocation.getter(#connectionError),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#connectionError),
            ),
          )
          as String);

  @override
  String get unknownError =>
      (super.noSuchMethod(
            Invocation.getter(#unknownError),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#unknownError),
            ),
          )
          as String);

  @override
  String get badCertificate =>
      (super.noSuchMethod(
            Invocation.getter(#badCertificate),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#badCertificate),
            ),
          )
          as String);

  @override
  String get somethingWentWrong =>
      (super.noSuchMethod(
            Invocation.getter(#somethingWentWrong),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#somethingWentWrong),
            ),
          )
          as String);

  @override
  String get validationFunctions____________ =>
      (super.noSuchMethod(
            Invocation.getter(#validationFunctions____________),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#validationFunctions____________),
            ),
          )
          as String);

  @override
  String get pleaseEnterName =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterName),
            ),
          )
          as String);

  @override
  String get pleaseEnterUserName =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterUserName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterUserName),
            ),
          )
          as String);

  @override
  String get userNameLength =>
      (super.noSuchMethod(
            Invocation.getter(#userNameLength),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#userNameLength),
            ),
          )
          as String);

  @override
  String get userNameRules =>
      (super.noSuchMethod(
            Invocation.getter(#userNameRules),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#userNameRules),
            ),
          )
          as String);

  @override
  String get pleaseEnterFirstName =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterFirstName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterFirstName),
            ),
          )
          as String);

  @override
  String get pleaseEnterLastName =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterLastName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterLastName),
            ),
          )
          as String);

  @override
  String get namesRules =>
      (super.noSuchMethod(
            Invocation.getter(#namesRules),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#namesRules),
            ),
          )
          as String);

  @override
  String get pleaseEnterEmail =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterEmail),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterEmail),
            ),
          )
          as String);

  @override
  String get pleaseEnterValidEmail =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterValidEmail),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterValidEmail),
            ),
          )
          as String);

  @override
  String get pleaseEnterPhoneNumber =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterPhoneNumber),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterPhoneNumber),
            ),
          )
          as String);

  @override
  String get phoneNumberRules =>
      (super.noSuchMethod(
            Invocation.getter(#phoneNumberRules),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#phoneNumberRules),
            ),
          )
          as String);

  @override
  String get pleaseEnterPassword =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterPassword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterPassword),
            ),
          )
          as String);

  @override
  String get passwordLength =>
      (super.noSuchMethod(
            Invocation.getter(#passwordLength),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#passwordLength),
            ),
          )
          as String);

  @override
  String get uppercaseRulePassword =>
      (super.noSuchMethod(
            Invocation.getter(#uppercaseRulePassword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#uppercaseRulePassword),
            ),
          )
          as String);

  @override
  String get lowercaseRulePassword =>
      (super.noSuchMethod(
            Invocation.getter(#lowercaseRulePassword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#lowercaseRulePassword),
            ),
          )
          as String);

  @override
  String get digitRulePassword =>
      (super.noSuchMethod(
            Invocation.getter(#digitRulePassword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#digitRulePassword),
            ),
          )
          as String);

  @override
  String get specialCharactersRulePassword =>
      (super.noSuchMethod(
            Invocation.getter(#specialCharactersRulePassword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#specialCharactersRulePassword),
            ),
          )
          as String);

  @override
  String get pleaseConfirmPassword =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseConfirmPassword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#pleaseConfirmPassword),
            ),
          )
          as String);

  @override
  String get namesLengthRule =>
      (super.noSuchMethod(
            Invocation.getter(#namesLengthRule),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#namesLengthRule),
            ),
          )
          as String);

  @override
  String get noMatch =>
      (super.noSuchMethod(
            Invocation.getter(#noMatch),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noMatch),
            ),
          )
          as String);

  @override
  String get pleaseEnterAddress =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterAddress),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterAddress),
            ),
          )
          as String);

  @override
  String get forgetPassword____________ =>
      (super.noSuchMethod(
            Invocation.getter(#forgetPassword____________),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#forgetPassword____________),
            ),
          )
          as String);

  @override
  String get emailHint =>
      (super.noSuchMethod(
            Invocation.getter(#emailHint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#emailHint),
            ),
          )
          as String);

  @override
  String get passwordHint =>
      (super.noSuchMethod(
            Invocation.getter(#passwordHint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#passwordHint),
            ),
          )
          as String);

  @override
  String get confirmPasswordHint =>
      (super.noSuchMethod(
            Invocation.getter(#confirmPasswordHint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#confirmPasswordHint),
            ),
          )
          as String);

  @override
  String get gender =>
      (super.noSuchMethod(
            Invocation.getter(#gender),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#gender),
            ),
          )
          as String);

  @override
  String get removedImage =>
      (super.noSuchMethod(
            Invocation.getter(#removedImage),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#removedImage),
            ),
          )
          as String);

  @override
  String get forgetPasswordDescription =>
      (super.noSuchMethod(
            Invocation.getter(#forgetPasswordDescription),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#forgetPasswordDescription),
            ),
          )
          as String);

  @override
  String get confirm =>
      (super.noSuchMethod(
            Invocation.getter(#confirm),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#confirm),
            ),
          )
          as String);

  @override
  String get codeSendTitle =>
      (super.noSuchMethod(
            Invocation.getter(#codeSendTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#codeSendTitle),
            ),
          )
          as String);

  @override
  String get otpScreenTitle =>
      (super.noSuchMethod(
            Invocation.getter(#otpScreenTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#otpScreenTitle),
            ),
          )
          as String);

  @override
  String get otpScreenDescription =>
      (super.noSuchMethod(
            Invocation.getter(#otpScreenDescription),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#otpScreenDescription),
            ),
          )
          as String);

  @override
  String get didNotReceiveOtp =>
      (super.noSuchMethod(
            Invocation.getter(#didNotReceiveOtp),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#didNotReceiveOtp),
            ),
          )
          as String);

  @override
  String get resend =>
      (super.noSuchMethod(
            Invocation.getter(#resend),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#resend),
            ),
          )
          as String);

  @override
  String get codeValid =>
      (super.noSuchMethod(
            Invocation.getter(#codeValid),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#codeValid),
            ),
          )
          as String);

  @override
  String get codeNotValid =>
      (super.noSuchMethod(
            Invocation.getter(#codeNotValid),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#codeNotValid),
            ),
          )
          as String);

  @override
  String get resetPasswordScreenDescription =>
      (super.noSuchMethod(
            Invocation.getter(#resetPasswordScreenDescription),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#resetPasswordScreenDescription),
            ),
          )
          as String);

  @override
  String get resetPasswordScreenTitle =>
      (super.noSuchMethod(
            Invocation.getter(#resetPasswordScreenTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#resetPasswordScreenTitle),
            ),
          )
          as String);

  @override
  String get newPassword =>
      (super.noSuchMethod(
            Invocation.getter(#newPassword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#newPassword),
            ),
          )
          as String);

  @override
  String get confirmNewPassword =>
      (super.noSuchMethod(
            Invocation.getter(#confirmNewPassword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#confirmNewPassword),
            ),
          )
          as String);

  @override
  String get yourPasswordChanged =>
      (super.noSuchMethod(
            Invocation.getter(#yourPasswordChanged),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#yourPasswordChanged),
            ),
          )
          as String);

  @override
  String get enterEmail =>
      (super.noSuchMethod(
            Invocation.getter(#enterEmail),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#enterEmail),
            ),
          )
          as String);

  @override
  String get enterPassword =>
      (super.noSuchMethod(
            Invocation.getter(#enterPassword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#enterPassword),
            ),
          )
          as String);

  @override
  String get forgetPassword =>
      (super.noSuchMethod(
            Invocation.getter(#forgetPassword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#forgetPassword),
            ),
          )
          as String);

  @override
  String get pleaseEnterValidAddress =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterValidAddress),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterValidAddress),
            ),
          )
          as String);

  @override
  String get skip =>
      (super.noSuchMethod(
            Invocation.getter(#skip),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#skip)),
          )
          as String);

  @override
  String get back =>
      (super.noSuchMethod(
            Invocation.getter(#back),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#back)),
          )
          as String);

  @override
  String get doIt =>
      (super.noSuchMethod(
            Invocation.getter(#doIt),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#doIt)),
          )
          as String);

  @override
  String get priceOfExcellence =>
      (super.noSuchMethod(
            Invocation.getter(#priceOfExcellence),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#priceOfExcellence),
            ),
          )
          as String);

  @override
  String get isDiscipline =>
      (super.noSuchMethod(
            Invocation.getter(#isDiscipline),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#isDiscipline),
            ),
          )
          as String);

  @override
  String get fitnessHasNeverBeenSo =>
      (super.noSuchMethod(
            Invocation.getter(#fitnessHasNeverBeenSo),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#fitnessHasNeverBeenSo),
            ),
          )
          as String);

  @override
  String get muchFun =>
      (super.noSuchMethod(
            Invocation.getter(#muchFun),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#muchFun),
            ),
          )
          as String);

  @override
  String get noMoreExcuses =>
      (super.noSuchMethod(
            Invocation.getter(#noMoreExcuses),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noMoreExcuses),
            ),
          )
          as String);

  @override
  String get doItNow =>
      (super.noSuchMethod(
            Invocation.getter(#doItNow),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#doItNow),
            ),
          )
          as String);

  @override
  String get loremIpsumDolorSitAmetConsectetureuUrna =>
      (super.noSuchMethod(
            Invocation.getter(#loremIpsumDolorSitAmetConsectetureuUrna),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#loremIpsumDolorSitAmetConsectetureuUrna),
            ),
          )
          as String);

  @override
  String get utGravidaQuisIdPretiumPurusMaurisMassa =>
      (super.noSuchMethod(
            Invocation.getter(#utGravidaQuisIdPretiumPurusMaurisMassa),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#utGravidaQuisIdPretiumPurusMaurisMassa),
            ),
          )
          as String);

  @override
  String get pleaseEnterValidRecipient =>
      (super.noSuchMethod(
            Invocation.getter(#pleaseEnterValidRecipient),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#pleaseEnterValidRecipient),
            ),
          )
          as String);

  @override
  String get home =>
      (super.noSuchMethod(
            Invocation.getter(#home),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#home)),
          )
          as String);

  @override
  String get chatAI =>
      (super.noSuchMethod(
            Invocation.getter(#chatAI),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#chatAI),
            ),
          )
          as String);

  @override
  String get forgotPassword =>
      (super.noSuchMethod(
            Invocation.getter(#forgotPassword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#forgotPassword),
            ),
          )
          as String);

  @override
  String get noAccount =>
      (super.noSuchMethod(
            Invocation.getter(#noAccount),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noAccount),
            ),
          )
          as String);

  @override
  String get success =>
      (super.noSuchMethod(
            Invocation.getter(#success),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#success),
            ),
          )
          as String);

  @override
  String get loginSuccessfully =>
      (super.noSuchMethod(
            Invocation.getter(#loginSuccessfully),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#loginSuccessfully),
            ),
          )
          as String);

  @override
  String get welcomeBack =>
      (super.noSuchMethod(
            Invocation.getter(#welcomeBack),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#welcomeBack),
            ),
          )
          as String);

  @override
  String get registerScreen________ =>
      (super.noSuchMethod(
            Invocation.getter(#registerScreen________),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#registerScreen________),
            ),
          )
          as String);

  @override
  String get heyThere =>
      (super.noSuchMethod(
            Invocation.getter(#heyThere),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#heyThere),
            ),
          )
          as String);

  @override
  String get createAnAccount =>
      (super.noSuchMethod(
            Invocation.getter(#createAnAccount),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#createAnAccount),
            ),
          )
          as String);

  @override
  String get register =>
      (super.noSuchMethod(
            Invocation.getter(#register),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#register),
            ),
          )
          as String);

  @override
  String get firstName =>
      (super.noSuchMethod(
            Invocation.getter(#firstName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#firstName),
            ),
          )
          as String);

  @override
  String get lastName =>
      (super.noSuchMethod(
            Invocation.getter(#lastName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#lastName),
            ),
          )
          as String);

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get password =>
      (super.noSuchMethod(
            Invocation.getter(#password),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#password),
            ),
          )
          as String);

  @override
  String get confirmPassword =>
      (super.noSuchMethod(
            Invocation.getter(#confirmPassword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#confirmPassword),
            ),
          )
          as String);

  @override
  String get or =>
      (super.noSuchMethod(
            Invocation.getter(#or),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#or)),
          )
          as String);

  @override
  String get alreadyHaveAccount =>
      (super.noSuchMethod(
            Invocation.getter(#alreadyHaveAccount),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#alreadyHaveAccount),
            ),
          )
          as String);

  @override
  String get login =>
      (super.noSuchMethod(
            Invocation.getter(#login),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#login),
            ),
          )
          as String);

  @override
  String get successfullyRegistered =>
      (super.noSuchMethod(
            Invocation.getter(#successfullyRegistered),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#successfullyRegistered),
            ),
          )
          as String);

  @override
  String get error =>
      (super.noSuchMethod(
            Invocation.getter(#error),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#error),
            ),
          )
          as String);

  @override
  String get tellUsAboutYourself =>
      (super.noSuchMethod(
            Invocation.getter(#tellUsAboutYourself),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#tellUsAboutYourself),
            ),
          )
          as String);

  @override
  String get weNeedToKnowYourGender =>
      (super.noSuchMethod(
            Invocation.getter(#weNeedToKnowYourGender),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#weNeedToKnowYourGender),
            ),
          )
          as String);

  @override
  String get howOldAreYou =>
      (super.noSuchMethod(
            Invocation.getter(#howOldAreYou),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#howOldAreYou),
            ),
          )
          as String);

  @override
  String get whatIsYourWeight =>
      (super.noSuchMethod(
            Invocation.getter(#whatIsYourWeight),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#whatIsYourWeight),
            ),
          )
          as String);

  @override
  String get thisHelpsUsCreateYourPersonalizedPlan =>
      (super.noSuchMethod(
            Invocation.getter(#thisHelpsUsCreateYourPersonalizedPlan),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#thisHelpsUsCreateYourPersonalizedPlan),
            ),
          )
          as String);

  @override
  String get whatIsYourHeight =>
      (super.noSuchMethod(
            Invocation.getter(#whatIsYourHeight),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#whatIsYourHeight),
            ),
          )
          as String);

  @override
  String get whatIsYourGoal =>
      (super.noSuchMethod(
            Invocation.getter(#whatIsYourGoal),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#whatIsYourGoal),
            ),
          )
          as String);

  @override
  String get yourPhysicalActivityLevel =>
      (super.noSuchMethod(
            Invocation.getter(#yourPhysicalActivityLevel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#yourPhysicalActivityLevel),
            ),
          )
          as String);

  @override
  String get activityLevel =>
      (super.noSuchMethod(
            Invocation.getter(#activityLevel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#activityLevel),
            ),
          )
          as String);

  @override
  String get male =>
      (super.noSuchMethod(
            Invocation.getter(#male),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#male)),
          )
          as String);

  @override
  String get female =>
      (super.noSuchMethod(
            Invocation.getter(#female),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#female),
            ),
          )
          as String);

  @override
  String get next =>
      (super.noSuchMethod(
            Invocation.getter(#next),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#next)),
          )
          as String);

  @override
  String get year =>
      (super.noSuchMethod(
            Invocation.getter(#year),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#year)),
          )
          as String);

  @override
  String get kg =>
      (super.noSuchMethod(
            Invocation.getter(#kg),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#kg)),
          )
          as String);

  @override
  String get cm =>
      (super.noSuchMethod(
            Invocation.getter(#cm),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#cm)),
          )
          as String);

  @override
  String get gainWeight =>
      (super.noSuchMethod(
            Invocation.getter(#gainWeight),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#gainWeight),
            ),
          )
          as String);

  @override
  String get loseWeight =>
      (super.noSuchMethod(
            Invocation.getter(#loseWeight),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#loseWeight),
            ),
          )
          as String);

  @override
  String get getFitter =>
      (super.noSuchMethod(
            Invocation.getter(#getFitter),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#getFitter),
            ),
          )
          as String);

  @override
  String get gainMoreFlexible =>
      (super.noSuchMethod(
            Invocation.getter(#gainMoreFlexible),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#gainMoreFlexible),
            ),
          )
          as String);

  @override
  String get learnTheBasic =>
      (super.noSuchMethod(
            Invocation.getter(#learnTheBasic),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#learnTheBasic),
            ),
          )
          as String);

  @override
  String get rookie =>
      (super.noSuchMethod(
            Invocation.getter(#rookie),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#rookie),
            ),
          )
          as String);

  @override
  String get beginner =>
      (super.noSuchMethod(
            Invocation.getter(#beginner),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#beginner),
            ),
          )
          as String);

  @override
  String get intermediate =>
      (super.noSuchMethod(
            Invocation.getter(#intermediate),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#intermediate),
            ),
          )
          as String);

  @override
  String get advanced =>
      (super.noSuchMethod(
            Invocation.getter(#advanced),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#advanced),
            ),
          )
          as String);

  @override
  String get trueBeast =>
      (super.noSuchMethod(
            Invocation.getter(#trueBeast),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#trueBeast),
            ),
          )
          as String);

  @override
  String get appSections___________ =>
      (super.noSuchMethod(
            Invocation.getter(#appSections___________),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#appSections___________),
            ),
          )
          as String);

  @override
  String get explore =>
      (super.noSuchMethod(
            Invocation.getter(#explore),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#explore),
            ),
          )
          as String);

  @override
  String get aiChat =>
      (super.noSuchMethod(
            Invocation.getter(#aiChat),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#aiChat),
            ),
          )
          as String);

  @override
  String get workouts =>
      (super.noSuchMethod(
            Invocation.getter(#workouts),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#workouts),
            ),
          )
          as String);

  @override
  String get profile =>
      (super.noSuchMethod(
            Invocation.getter(#profile),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#profile),
            ),
          )
          as String);

  @override
  String get sendOtp =>
      (super.noSuchMethod(
            Invocation.getter(#sendOtp),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#sendOtp),
            ),
          )
          as String);

  @override
  String get resetPassDesc =>
      (super.noSuchMethod(
            Invocation.getter(#resetPassDesc),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#resetPassDesc),
            ),
          )
          as String);

  @override
  String get createNewPassword =>
      (super.noSuchMethod(
            Invocation.getter(#createNewPassword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#createNewPassword),
            ),
          )
          as String);

  @override
  String get done =>
      (super.noSuchMethod(
            Invocation.getter(#done),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#done)),
          )
          as String);

  @override
  String get oTpCode =>
      (super.noSuchMethod(
            Invocation.getter(#oTpCode),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#oTpCode),
            ),
          )
          as String);

  @override
  String get enterOtpCode =>
      (super.noSuchMethod(
            Invocation.getter(#enterOtpCode),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#enterOtpCode),
            ),
          )
          as String);

  @override
  String get successEmailVerified =>
      (super.noSuchMethod(
            Invocation.getter(#successEmailVerified),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#successEmailVerified),
            ),
          )
          as String);

  @override
  String get foodRecommendation =>
      (super.noSuchMethod(
            Invocation.getter(#foodRecommendation),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#foodRecommendation),
            ),
          )
          as String);

  @override
  String get noVideoProvide =>
      (super.noSuchMethod(
            Invocation.getter(#noVideoProvide),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noVideoProvide),
            ),
          )
          as String);

  @override
  String get noFoodRecommendation =>
      (super.noSuchMethod(
            Invocation.getter(#noFoodRecommendation),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noFoodRecommendation),
            ),
          )
          as String);

  @override
  String get ingredients =>
      (super.noSuchMethod(
            Invocation.getter(#ingredients),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#ingredients),
            ),
          )
          as String);

  @override
  String get recommendation =>
      (super.noSuchMethod(
            Invocation.getter(#recommendation),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#recommendation),
            ),
          )
          as String);

  @override
  String get energy =>
      (super.noSuchMethod(
            Invocation.getter(#energy),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#energy),
            ),
          )
          as String);

  @override
  String get energyValue =>
      (super.noSuchMethod(
            Invocation.getter(#energyValue),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#energyValue),
            ),
          )
          as String);

  @override
  String get noWorkoutsAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#noWorkoutsAvailable),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noWorkoutsAvailable),
            ),
          )
          as String);

  @override
  String get homePage_________ =>
      (super.noSuchMethod(
            Invocation.getter(#homePage_________),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#homePage_________),
            ),
          )
          as String);

  @override
  String get startYourDayMessage =>
      (super.noSuchMethod(
            Invocation.getter(#startYourDayMessage),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#startYourDayMessage),
            ),
          )
          as String);

  @override
  String get category =>
      (super.noSuchMethod(
            Invocation.getter(#category),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#category),
            ),
          )
          as String);

  @override
  String get gym =>
      (super.noSuchMethod(
            Invocation.getter(#gym),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#gym)),
          )
          as String);

  @override
  String get fitness =>
      (super.noSuchMethod(
            Invocation.getter(#fitness),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#fitness),
            ),
          )
          as String);

  @override
  String get yoga =>
      (super.noSuchMethod(
            Invocation.getter(#yoga),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#yoga)),
          )
          as String);

  @override
  String get aerobics =>
      (super.noSuchMethod(
            Invocation.getter(#aerobics),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#aerobics),
            ),
          )
          as String);

  @override
  String get trainer =>
      (super.noSuchMethod(
            Invocation.getter(#trainer),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#trainer),
            ),
          )
          as String);

  @override
  String get recommendationToDay =>
      (super.noSuchMethod(
            Invocation.getter(#recommendationToDay),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#recommendationToDay),
            ),
          )
          as String);

  @override
  String get noData =>
      (super.noSuchMethod(
            Invocation.getter(#noData),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noData),
            ),
          )
          as String);

  @override
  String get upcomingWorkouts =>
      (super.noSuchMethod(
            Invocation.getter(#upcomingWorkouts),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#upcomingWorkouts),
            ),
          )
          as String);

  @override
  String get seeAll =>
      (super.noSuchMethod(
            Invocation.getter(#seeAll),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#seeAll),
            ),
          )
          as String);

  @override
  String get recommendationForYou =>
      (super.noSuchMethod(
            Invocation.getter(#recommendationForYou),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#recommendationForYou),
            ),
          )
          as String);

  @override
  String get changePassword =>
      (super.noSuchMethod(
            Invocation.getter(#changePassword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#changePassword),
            ),
          )
          as String);

  @override
  String get selectLanguage =>
      (super.noSuchMethod(
            Invocation.getter(#selectLanguage),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#selectLanguage),
            ),
          )
          as String);

  @override
  String get security =>
      (super.noSuchMethod(
            Invocation.getter(#security),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#security),
            ),
          )
          as String);

  @override
  String get privacyPolicy =>
      (super.noSuchMethod(
            Invocation.getter(#privacyPolicy),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#privacyPolicy),
            ),
          )
          as String);

  @override
  String get help =>
      (super.noSuchMethod(
            Invocation.getter(#help),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#help)),
          )
          as String);

  @override
  String get logout =>
      (super.noSuchMethod(
            Invocation.getter(#logout),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#logout),
            ),
          )
          as String);

  @override
  String get english =>
      (super.noSuchMethod(
            Invocation.getter(#english),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#english),
            ),
          )
          as String);

  @override
  String get areYouSureLogout =>
      (super.noSuchMethod(
            Invocation.getter(#areYouSureLogout),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#areYouSureLogout),
            ),
          )
          as String);

  @override
  String get logoutCancel =>
      (super.noSuchMethod(
            Invocation.getter(#logoutCancel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#logoutCancel),
            ),
          )
          as String);

  @override
  String get unknown =>
      (super.noSuchMethod(
            Invocation.getter(#unknown),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#unknown),
            ),
          )
          as String);

  @override
  String get editProfile =>
      (super.noSuchMethod(
            Invocation.getter(#editProfile),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#editProfile),
            ),
          )
          as String);

  @override
  String get updatedSuccessfully =>
      (super.noSuchMethod(
            Invocation.getter(#updatedSuccessfully),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#updatedSuccessfully),
            ),
          )
          as String);

  @override
  String get yourWeight =>
      (super.noSuchMethod(
            Invocation.getter(#yourWeight),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#yourWeight),
            ),
          )
          as String);

  @override
  String get tapToEdit =>
      (super.noSuchMethod(
            Invocation.getter(#tapToEdit),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#tapToEdit),
            ),
          )
          as String);

  @override
  String get yourGoal =>
      (super.noSuchMethod(
            Invocation.getter(#yourGoal),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#yourGoal),
            ),
          )
          as String);

  @override
  String get yourActivityLevel =>
      (super.noSuchMethod(
            Invocation.getter(#yourActivityLevel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#yourActivityLevel),
            ),
          )
          as String);

  @override
  String get update =>
      (super.noSuchMethod(
            Invocation.getter(#update),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#update),
            ),
          )
          as String);

  @override
  String hiUser(Object? userName) =>
      (super.noSuchMethod(
            Invocation.method(#hiUser, [userName]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#hiUser, [userName]),
            ),
          )
          as String);
}

/// A class which mocks [ValidateFunctions].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidateFunctions extends _i1.Mock implements _i16.ValidateFunctions {
  MockValidateFunctions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set appLocalizations(_i15.AppLocalizations? appLocalizations) =>
      super.noSuchMethod(
        Invocation.setter(#appLocalizations, appLocalizations),
        returnValueForMissingStub: null,
      );

  @override
  String? validationOfFirstOrLastName(
    String? inputText, {
    bool? isFirstName = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #validationOfFirstOrLastName,
              [inputText],
              {#isFirstName: isFirstName},
            ),
          )
          as String?);

  @override
  String? validationOfConfirmPassword(
    String? inputText,
    String? passwordToMatchWith,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validationOfConfirmPassword, [
              inputText,
              passwordToMatchWith,
            ]),
          )
          as String?);
}
