// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness/test/modules/authentication/data/data_sources_imp/login/login_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:super_fitness/modules/authentication/data/api/api_client/auth_api_client.dart'
    as _i4;
import 'package:super_fitness/modules/authentication/data/models/forget_password/forget_password_response.dart'
    as _i6;
import 'package:super_fitness/modules/authentication/data/models/login/login.dart'
    as _i3;
import 'package:super_fitness/modules/authentication/data/models/register/response/register_response_dto.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegisterResponseDto_0 extends _i1.SmartFake
    implements _i2.RegisterResponseDto {
  _FakeRegisterResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginModel_1 extends _i1.SmartFake implements _i3.LoginModel {
  _FakeLoginModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiClient extends _i1.Mock implements _i4.AuthApiClient {
  MockAuthApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.ForgetPasswordResponse?> forgetPassword(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [body]),
            returnValue: _i5.Future<_i6.ForgetPasswordResponse?>.value(),
          )
          as _i5.Future<_i6.ForgetPasswordResponse?>);

  @override
  _i5.Future<_i6.ForgetPasswordResponse?> resetPassword(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [body]),
            returnValue: _i5.Future<_i6.ForgetPasswordResponse?>.value(),
          )
          as _i5.Future<_i6.ForgetPasswordResponse?>);

  @override
  _i5.Future<_i6.ForgetPasswordResponse?> resetCode(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetCode, [body]),
            returnValue: _i5.Future<_i6.ForgetPasswordResponse?>.value(),
          )
          as _i5.Future<_i6.ForgetPasswordResponse?>);

  @override
  _i5.Future<_i2.RegisterResponseDto> register(Map<String, dynamic>? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i5.Future<_i2.RegisterResponseDto>.value(
              _FakeRegisterResponseDto_0(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.RegisterResponseDto>);

  @override
  _i5.Future<_i3.LoginModel> login(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#login, [body]),
            returnValue: _i5.Future<_i3.LoginModel>.value(
              _FakeLoginModel_1(this, Invocation.method(#login, [body])),
            ),
          )
          as _i5.Future<_i3.LoginModel>);
}
