// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness/test/modules/home/ui/pages/profile_page/ui/view_model/profile_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:super_fitness/core/apis/api_result/api_result.dart' as _i4;
import 'package:super_fitness/modules/authentication/domain/entities/login/login_data_response_entity.dart'
    as _i5;
import 'package:super_fitness/modules/authentication/domain/usecase/login/login_local.dart'
    as _i7;
import 'package:super_fitness/modules/home/ui/pages/profile_page/domain/use_cases/get_profile_data.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetProfileDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileDataUseCase extends _i1.Mock
    implements _i2.GetProfileDataUseCase {
  MockGetProfileDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.UserEntity?>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i3.Future<_i4.ApiResult<_i5.UserEntity?>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.UserEntity?>>(
                this,
                Invocation.method(#execute, []),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.UserEntity?>>);
}

/// A class which mocks [StoreLoginLocalUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoreLoginLocalUseCase extends _i1.Mock
    implements _i7.StoreLoginLocalUseCase {
  MockStoreLoginLocalUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(_i5.LoginEntity? loginEntity) =>
      (super.noSuchMethod(
            Invocation.method(#call, [loginEntity]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.LoginEntity?> getLocalData() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalData, []),
            returnValue: _i3.Future<_i5.LoginEntity?>.value(),
          )
          as _i3.Future<_i5.LoginEntity?>);

  @override
  _i3.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
