// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness/test/modules/home/ui/pages/profile_page/change_password_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:super_fitness/core/apis/api_result/api_result.dart' as _i5;
import 'package:super_fitness/modules/home/domain/entities/change_password/change_password_response_entity.dart'
    as _i6;
import 'package:super_fitness/modules/home/domain/repositories_contracts/change_password_repo_contract.dart'
    as _i2;
import 'package:super_fitness/modules/home/domain/use_cases/change_password/change_password_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChangePasswordRepoContract_0 extends _i1.SmartFake
    implements _i2.ChangePasswordRepoContract {
  _FakeChangePasswordRepoContract_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChangePasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangePasswordUseCase extends _i1.Mock
    implements _i3.ChangePasswordUseCase {
  MockChangePasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChangePasswordRepoContract get changePasswordRepoContract =>
      (super.noSuchMethod(
            Invocation.getter(#changePasswordRepoContract),
            returnValue: _FakeChangePasswordRepoContract_0(
              this,
              Invocation.getter(#changePasswordRepoContract),
            ),
          )
          as _i2.ChangePasswordRepoContract);

  @override
  set changePasswordRepoContract(
    _i2.ChangePasswordRepoContract? _changePasswordRepoContract,
  ) => super.noSuchMethod(
    Invocation.setter(#changePasswordRepoContract, _changePasswordRepoContract),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.ApiResult<_i6.ChangePasswordResponseEntity>> call(
    String? password,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [password, newPassword]),
            returnValue: _i4.Future<
              _i5.ApiResult<_i6.ChangePasswordResponseEntity>
            >.value(
              _i7.dummyValue<_i5.ApiResult<_i6.ChangePasswordResponseEntity>>(
                this,
                Invocation.method(#call, [password, newPassword]),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.ChangePasswordResponseEntity>>);
}
