// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness/test/modules/authentication/ui/forget_password/register/register_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_auth/firebase_auth.dart' as _i10;
import 'package:google_sign_in/google_sign_in.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:super_fitness/core/apis/api_result/api_result.dart' as _i5;
import 'package:super_fitness/core/utilities/google_sign_in/google_sign_in_handler.dart'
    as _i12;
import 'package:super_fitness/modules/authentication/data/models/user/user_dto.dart'
    as _i11;
import 'package:super_fitness/modules/authentication/domain/entities/register/request/register_request_entity.dart'
    as _i7;
import 'package:super_fitness/modules/authentication/domain/entities/register/response/register_response_entity.dart'
    as _i6;
import 'package:super_fitness/modules/authentication/domain/use_cases/firebase_auth/google/sign_up/sign_up_with_google_account.dart'
    as _i9;
import 'package:super_fitness/modules/authentication/domain/use_cases/register/register_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGoogleSignInAuthentication_0 extends _i1.SmartFake
    implements _i2.GoogleSignInAuthentication {
  _FakeGoogleSignInAuthentication_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RegisterUserCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUserCase extends _i1.Mock implements _i3.RegisterUserCase {
  MockRegisterUserCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResult<_i6.RegisterResponseEntity>> call({
    required _i7.RegisterRequestEntity? registerRequestEntity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #registerRequestEntity: registerRequestEntity,
            }),
            returnValue:
                _i4.Future<_i5.ApiResult<_i6.RegisterResponseEntity>>.value(
                  _i8.dummyValue<_i5.ApiResult<_i6.RegisterResponseEntity>>(
                    this,
                    Invocation.method(#call, [], {
                      #registerRequestEntity: registerRequestEntity,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.ApiResult<_i6.RegisterResponseEntity>>);
}

/// A class which mocks [SignUpWithGoogleAccountUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpWithGoogleAccountUseCase extends _i1.Mock
    implements _i9.SignUpWithGoogleAccountUseCase {
  MockSignUpWithGoogleAccountUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResult<_i10.UserCredential>> call(
    _i2.GoogleSignInAccount? googleUserAccount,
    _i11.UserDto? userDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [googleUserAccount, userDto]),
            returnValue: _i4.Future<_i5.ApiResult<_i10.UserCredential>>.value(
              _i8.dummyValue<_i5.ApiResult<_i10.UserCredential>>(
                this,
                Invocation.method(#call, [googleUserAccount, userDto]),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i10.UserCredential>>);
}

/// A class which mocks [GoogleSignInHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInHandler extends _i1.Mock
    implements _i12.GoogleSignInHandler {
  MockGoogleSignInHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GoogleSignInAccount?> getUserGoogleAccount() =>
      (super.noSuchMethod(
            Invocation.method(#getUserGoogleAccount, []),
            returnValue: _i4.Future<_i2.GoogleSignInAccount?>.value(),
          )
          as _i4.Future<_i2.GoogleSignInAccount?>);
}

/// A class which mocks [GoogleSignInAccount].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInAccount extends _i1.Mock
    implements _i2.GoogleSignInAccount {
  MockGoogleSignInAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i4.Future<_i2.GoogleSignInAuthentication> get authentication =>
      (super.noSuchMethod(
            Invocation.getter(#authentication),
            returnValue: _i4.Future<_i2.GoogleSignInAuthentication>.value(
              _FakeGoogleSignInAuthentication_0(
                this,
                Invocation.getter(#authentication),
              ),
            ),
          )
          as _i4.Future<_i2.GoogleSignInAuthentication>);

  @override
  _i4.Future<Map<String, String>> get authHeaders =>
      (super.noSuchMethod(
            Invocation.getter(#authHeaders),
            returnValue: _i4.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<void> clearAuthCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthCache, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [UserCredential].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserCredential extends _i1.Mock implements _i10.UserCredential {
  MockUserCredential() {
    _i1.throwOnMissingStub(this);
  }
}
