// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness/test/modules/authentication/data/repositories_imp/login/login_repo_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:super_fitness/core/apis/api_result/api_result.dart' as _i4;
import 'package:super_fitness/modules/authentication/data/data_sources_contracts/login/login.dart'
    as _i2;
import 'package:super_fitness/modules/authentication/domain/entities/login/login_data_response_entity.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LoginOnlineDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginOnlineDataSource extends _i1.Mock
    implements _i2.LoginOnlineDataSource {
  MockLoginOnlineDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.LoginEntity>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i3.Future<_i4.ApiResult<_i5.LoginEntity>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.LoginEntity>>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.LoginEntity>>);
}
