// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness/test/modules/edit_profile/data/repo_impl/get_data_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:super_fitness/core/apis/api_result/api_result.dart' as _i4;
import 'package:super_fitness/modules/edit_profile/data/datasource/get_data.dart'
    as _i2;
import 'package:super_fitness/modules/edit_profile/domain/entity/get_data_entity.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetLoggedDriverDataOnlineDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLoggedDriverDataOnlineDataSource extends _i1.Mock
    implements _i2.GetLoggedDriverDataOnlineDataSource {
  MockGetLoggedDriverDataOnlineDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.GetDataEntity>> getLoggedDriverData() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedDriverData, []),
            returnValue: _i3.Future<_i4.ApiResult<_i5.GetDataEntity>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.GetDataEntity>>(
                this,
                Invocation.method(#getLoggedDriverData, []),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.GetDataEntity>>);
}
