// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness/test/modules/edit_profile/data/repo_impl/image_upload_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:super_fitness/core/apis/api_result/api_result.dart' as _i4;
import 'package:super_fitness/modules/edit_profile/data/datasource/upload_image.dart'
    as _i2;
import 'package:super_fitness/modules/edit_profile/domain/entity/upload_image_response_entity.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UploadImageOnlineDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadImageOnlineDataSource extends _i1.Mock
    implements _i2.UploadImageOnlineDataSource {
  MockUploadImageOnlineDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.UploadImageResponseEntity?>> uploadProfileImage({
    required _i6.File? imageFile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, [], {#imageFile: imageFile}),
            returnValue:
                _i3.Future<_i4.ApiResult<_i5.UploadImageResponseEntity?>>.value(
                  _i7.dummyValue<_i4.ApiResult<_i5.UploadImageResponseEntity?>>(
                    this,
                    Invocation.method(#uploadProfileImage, [], {
                      #imageFile: imageFile,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i5.UploadImageResponseEntity?>>);
}
