// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness/test/modules/food/ui/view_model/food_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:super_fitness/core/apis/api_result/api_result.dart' as _i4;
import 'package:super_fitness/modules/food/domain/entities/food_categories_entity.dart'
    as _i8;
import 'package:super_fitness/modules/food/domain/entities/meal_entity.dart'
    as _i5;
import 'package:super_fitness/modules/food/domain/use_cases/filter_meals_by_category_name_use_case.dart'
    as _i2;
import 'package:super_fitness/modules/food/domain/use_cases/get_food_categories_use_case.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FilterMealsByCategoryNameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilterMealsByCategoryNameUseCase extends _i1.Mock
    implements _i2.FilterMealsByCategoryNameUseCase {
  MockFilterMealsByCategoryNameUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<List<_i5.MealEntity>>> call(String? categoryName) =>
      (super.noSuchMethod(
            Invocation.method(#call, [categoryName]),
            returnValue: _i3.Future<_i4.ApiResult<List<_i5.MealEntity>>>.value(
              _i6.dummyValue<_i4.ApiResult<List<_i5.MealEntity>>>(
                this,
                Invocation.method(#call, [categoryName]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<List<_i5.MealEntity>>>);
}

/// A class which mocks [GetFoodCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFoodCategoriesUseCase extends _i1.Mock
    implements _i7.GetFoodCategoriesUseCase {
  MockGetFoodCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<List<_i8.FoodCategoryEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.ApiResult<List<_i8.FoodCategoryEntity>>>.value(
                  _i6.dummyValue<_i4.ApiResult<List<_i8.FoodCategoryEntity>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<List<_i8.FoodCategoryEntity>>>);
}
