// Mocks generated by Mockito 5.4.6 from annotations
// in super_fitness/test/modules/food_details/data/datasource_impl/food_details_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:super_fitness/modules/food_details/data/api/api_client/food_details_api_client.dart'
    as _i3;
import 'package:super_fitness/modules/food_details/data/models/food_details.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFoodDetailsModel_0 extends _i1.SmartFake
    implements _i2.FoodDetailsModel {
  _FakeFoodDetailsModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FoodDetailsApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodDetailsApiClient extends _i1.Mock
    implements _i3.FoodDetailsApiClient {
  MockFoodDetailsApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.FoodDetailsModel> getFoodDetails(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodDetails, [id]),
            returnValue: _i4.Future<_i2.FoodDetailsModel>.value(
              _FakeFoodDetailsModel_0(
                this,
                Invocation.method(#getFoodDetails, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.FoodDetailsModel>);
}
